project:
  type: default

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "Sumário"
    toc-depth: 3
    code-fold: true
    code-summary: "Ver código"
    embed-resources: true
    fig-align: center

execute:
  freeze: auto
  warning: false
  message: false
